public  class Player {
    public void playing() {
        string player1Name='Ali';
        system.debug(player1Name);
        Integer player1Namelength=player1Name.length();
        system.debug(player1Namelength);

        string player2Name='Ahmet';
        system.debug(player2Name);
        integer player2Namelength=player2Name.length();
        system.debug(player2Namelength);

        string player3Name='Ronaldo';
        system.debug(Player3Name);
        integer player3Namelength=player3Name.length();
        system.debug(player3Namelength);
        string upperPlayer3Name=player3Name.toUpperCase();

        string player4Name='Messi';
        system.debug(player4Name);
        integer player4Namelength=player4Name.length();
        system.debug(player4Namelength);


        string player5Name='hagi';
        system.debug(player5Name);
        integer player5Namelength=player5Name.length();
        system.debug(player5Namelength);



    }
}