List<Decimal>value=new List<Decimal>{ 10.5,12.5,17};
system.debug(OperationsHelper.SumList(value));
system.debug(OperationsHelper.averList(value));
system.debug(OperationsHelper.highList(value));



OperationsHelper  o1=new OperationsHelper();
system.debug(o1.sumofPositive(5));
system.debug(o1.smallestOutOfThreeNumbers(8, 10 , 6));
system.debug(o1.largestOutOfTwoNumbers(3.5, 4.8));
//o1.largestOutOfTwoNumbers(x, y);
