Planets pl=new Planets();
pl.name='jupiter';
pl.planetNumber=8;
pl.numberOfMoons=8;
system.debug(pl);





Planets ea=new Planets();
ea.name='Earth';
ea.planetNumber=6;
ea.numberOfMoons=4;
system.debug(ea);


Planets ge=new Planets();
ge.name='Mars';
ge.planetNumber=8;
ge.numberOfMoons=2;
system.debug('name is ' + ge.name + 'planet number is '+ ge.planetNumber + 'number of moons is  '+  ge.numberOfMoons );


